version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-deps:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      gha-deps:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]
